source 'https://github.com/CocoaPods/Specs.git'
# source 'git@git.xiaojukeji.com:one-ios/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'DemoPresentation' do
    # pod "ONEUIKit"
    pod 'MagicalRecord'
    pod 'ObjectiveSugar'
end
